#! /bin/bash
#
# Run dtiinit Gear
# Built to flywheel-v0 spec.
#
CONTAINER="[scitran/dtiinit]"

# Configure the ENV
export FSLOUTPUTTYPE=NIFTI_GZ
export LD_LIBRARY_PATH=/opt/mcr/v82/runtime/glnxa64:/opt/mcr/v82/bin/glnxa64:/opt/mcr/v82/sys/os/glnxa64:/opt/mcr/v82/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/opt/mcr/v82/sys/java/jre/glnxa64/jre/lib/amd64/server:/opt/mcr/v82/sys/java/jre/glnxa64/jre/lib/amd64:$LD_LIBRARY_PATH
export XAPPLRESDIR=/opt/mcr/v82/X11/app-defaults

FLYWHEEL_BASE=/flywheel/v0
OUTPUT_DIR=$FLYWHEEL_BASE/output
NIFTI_DIR=$FLYWHEEL_BASE/nifti
BVEC_DIR=$FLYWHEEL_BASE/bvec
BVAL_DIR=$FLYWHEEL_BASE/bval
JSON_DIR=$FLYWHEEL_BASE/json
WORK_DIR=$FLYWHEEL_BASE/input

echo -e "$CONTAINER  Initiated"

if [[ ! -d "$OUTPUT_DIR" ]]
    then
        echo "$CONTAINER  $OUTPUT_DIR not found!"
        exit 1
fi

# Make the directories
mkdir $WORK_DIR
mkdir $JSON_DIR

# Convert the config json to a dtiinit_params json file
$FLYWHEEL_BASE/parse_config.py --input_file ${FLYWHEEL_BASE}/config.json --output_file ${JSON_DIR}/dtiInit-params.json --input_dir ${WORK_DIR} --output_dir ${OUTPUT_DIR}

# Make sure the params file is saved with the output
cp ${JSON_DIR}/dtiInit-params.json ${OUTPUT_DIR}

# Do the work
cp $NIFTI_DIR/* $BVEC_DIR/* $BVAL_DIR/* $JSON_DIR/* $WORK_DIR
/usr/local/bin/dtiInit $WORK_DIR 2>&1 | tee $OUTPUT_DIR/dtiInit-log.txt

# Get a list of the files in the output directory
outputs=$(find $OUTPUT_DIR/* -maxdepth 0 -type f)

# If outputs exist, generate metadata, and exit
if [[ -z $outputs ]]
    then
        echo "$CONTAINER  No results found in output directory... Exiting"
        exit 1
    else
        cd $OUTPUT_DIR
        $FLYWHEEL_BASE/metadata_create.py $OUTPUT_DIR $CONTAINER
        echo -e "$CONTAINER  Wrote: `ls`"
        echo -e "$CONTAINER  Done!"
fi

exit 0
